# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 9
version: "{build}"
build: off
deploy: off
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
test_script:
  - cmd: "yarn test"
